# Generated by Django 4.2.4 on 2023-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GDP",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("updated_at", models.DateField()),
            ],
            options={
                "db_table": "gdp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LaborProductivity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateField()),
                ("value", models.BigIntegerField()),
                ("period", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
                ("updated_at", models.DateField()),
            ],
            options={
                "db_table": "labor_productivity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LaborProductivityActivityType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "labor_productivity_activity_types",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "regions",
                "managed": False,
            },
        ),
    ]
