# Generated by Django 4.2.4 on 2023-09-27 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="economic_index",
            name="path",
        ),
        migrations.AddField(
            model_name="economic_index",
            name="not_disabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="economic_index",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, null=True)),
                (
                    "macro_economic_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.economic_index",
                    ),
                ),
            ],
        ),
    ]
