# Generated by Django 4.2.4 on 2023-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contentname_indicatorsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'economic_indices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'topics',
                'managed': False,
            },
        ),
    ]
