# Generated by Django 4.2.4 on 2023-08-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contentname_indicatorsname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsname',
            name='macro_id',
        ),
        migrations.DeleteModel(
            name='ContentName',
        ),
        migrations.DeleteModel(
            name='IndicatorsName',
        ),
    ]
