# Generated by Django 4.2.4 on 2023-08-22 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_indicatorsname_macro_id_delete_contentname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('macro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentname')),
            ],
        ),
    ]
